[[redirects]]
    from = "/spotify"              
    to = "https://open.spotify.com/album/0Ela0hmFmPSvGfBAo4o2Yu?si=9j8elrT9TmGXkpR4DtXYZQ"


 [[redirects]]
    from = "/youtubemusic"
    to = "https://music.youtube.com/playlist?list=OLAK5uy_k3h8f_jx9xDReCiC0SRqq_kKkZ5_gTE8A"

[[redirects]]
    from = "/amazon"
    to = "https://www.amazon.com/Beyond-Speedy/dp/B08FXP3HSN/ref=sr_1_8?dchild=1&keywords=speedy+beyond&qid=1599201664&sr=8-8"

 [[redirects]]
    from = "/apple"
    to = "https://music.apple.com/us/album/beyond/1527765241"

 [[redirects]]
    from = "/soundcloud"
    to = "https://soundcloud.com/thisisspeedy"

 [[redirects]]
    from = "/napster"
    to = "https://us.napster.com/artist/speedy/album/beyond-504428358"


 [[redirects]]
    from = "/youtube"
    to = "https://www.youtube.com/channel/UCfgBkqVDWU5eQQEBV5bCOwA"    

 [[redirects]]
    from = "/twitter"
    to = "https://twitter.com/speedytheartist"    

 [[redirects]]
    from = "/instagram"
    to = "https://www.instagram.com/speedy_on_ig/"        