backend:
    name: git-gateway
    branch: master

local_backend:
    url: http://localhost:8082/api/v1
    allowed_hosts: ['192.168.0.1']

media_folder: static/img
public_folder: /img

collections:
    - name: 'music'
      label: 'music'
      folder: 'content/music'
      create: true
      slug: 'index'
      editor:
          preview: false
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Release Date', name: 'date', widget: 'datetime' }
          - { label: 'Artwork', name: 'image', widget: 'image' }
          - { label: 'Spotify Url', name: 'spotify', widget: 'string' }

    - name: 'bio'
      label: 'bio'
      folder: 'content/bio'
      create: true
      slug: 'index'
      editor:
          preview: false
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'text' }
    - name: 'links'
      label: 'links'
      folder: 'content/links'
      create: true
      slug: 'index'
      editor:
          preview: false
      widget: 'list'
      fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
          - {
                label: 'type',
                name: 'type',
                widget: 'select',
                options: ['Social', 'Music', 'Support', 'Tour', 'Video'],
                default: ['Social'],
            }
    - name: 'news'
      label: 'news'
      folder: 'content/news'
      media_folder: '/'
      public_folder: '/'
      create: true
      slug: 'index'
      editor:
          preview: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Date', name: 'date', widget: 'datetime' }
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'URL', name: 'url', widget: 'string' }
          - { label: 'Blurb', name: 'blurb', widget: 'text' }
